# Generated by Django 6.1.1 on 2026-09-22 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("txnid", models.CharField(db_index=True, max_length=25, unique=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("productinfo", models.CharField(max_length=255)),
                ("firstname", models.CharField(max_length=60)),
                ("lastname", models.CharField(blank=True, max_length=60)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=15)),
                (
                    "reference_id",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("pending", "Pending"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                            ("bounced", "Bounced"),
                            ("dropped", "Dropped"),
                            ("refunded", "Refunded"),
                            ("partially_refunded", "Partially refunded"),
                        ],
                        db_index=True,
                        default="created",
                        max_length=32,
                    ),
                ),
                ("payu_id", models.CharField(blank=True, max_length=64)),
                ("bank_ref_num", models.CharField(blank=True, max_length=64)),
                ("payment_mode", models.CharField(blank=True, max_length=32)),
                ("error_code", models.CharField(blank=True, max_length=64)),
                ("error_message", models.CharField(blank=True, max_length=255)),
                ("request_hash", models.CharField(blank=True, max_length=128)),
                ("udf1", models.CharField(blank=True, max_length=255)),
                ("udf2", models.CharField(blank=True, max_length=255)),
                ("udf3", models.CharField(blank=True, max_length=255)),
                ("udf4", models.CharField(blank=True, max_length=255)),
                ("udf5", models.CharField(blank=True, max_length=255)),
                ("gateway_status", models.CharField(blank=True, max_length=32)),
                ("request_payload", models.JSONField(blank=True, default=dict)),
                ("response_payload", models.JSONField(blank=True, default=dict)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Refund",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(max_length=23, unique=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requested", "Requested"),
                            ("pending", "Pending"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                        ],
                        default="requested",
                        max_length=16,
                    ),
                ),
                ("payu_request_id", models.CharField(blank=True, max_length=64)),
                ("message", models.CharField(blank=True, max_length=255)),
                ("response_payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="refunds",
                        to="payments.payment",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
